services:
  next:
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
        - DATABASE_URL=${DATABASE_URL}
        - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    ports:
      - "3000:3000"
    env_file:
      - ./.env.production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge