name: CI Pipeline

on: push

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v5
      - name: User Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      
      - name: Install Dependencies
        run: bun install
      
      - name: Build Project
        run: bun run build
      
      - name: Run Tests
        run: bun run test
